import type { Category, Product } from "@/lib/types";

export const categories: Category[] = [
  {
    id: "cat-paper",
    name: "Tissue & Paper Wholesale",
    slug: "tissue-paper-products",
    description: "Carton-based tissue and paper supplies for businesses and institutions.",
    icon: "PackageCheck",
    tone: "sand",
  },
  {
    id: "cat-washroom",
    name: "Washroom Supplies",
    slug: "washroom-supplies",
    description: "Hand wash, sanitizers and washroom hygiene essentials by carton.",
    icon: "Droplets",
    tone: "mint",
  },
  {
    id: "cat-cleaning",
    name: "Cleaning Products",
    slug: "cleaning-products",
    description: "Floor cleaners, sprays and professional cleaning solutions.",
    icon: "Sparkles",
    tone: "sky",
  },
  {
    id: "cat-personal",
    name: "Personal Care",
    slug: "personal-care",
    description: "Soaps, hand wash and personal hygiene products for bulk supply.",
    icon: "Heart",
    tone: "rose",
  },
  {
    id: "cat-disposable",
    name: "Disposable Items",
    slug: "disposable-items",
    description: "Garbage bags, gloves and single-use hygiene disposables.",
    icon: "Trash2",
    tone: "amber",
  },
];

// Two-level collection structure; packing and prices are managed separately.
categories.push(
  { id: "cat-facial", parentId: "cat-paper", name: "Facial Tissues", slug: "facial-tissues", description: "Boxed tissues and pop-up packs for everyday use.", icon: "PackageCheck", tone: "sand" },
  { id: "cat-soft", parentId: "cat-paper", name: "Soft Pack Tissues", slug: "soft-pack-tissues", description: "Soft pack tissues supplied by the carton.", icon: "PackageCheck", tone: "sand" },
  { id: "cat-rolls", parentId: "cat-paper", name: "Tissue Rolls", slug: "tissue-rolls", description: "Paper rolls for washrooms and shared facilities.", icon: "PackageCheck", tone: "sand" },
  { id: "cat-napkins", parentId: "cat-paper", name: "Paper Napkins", slug: "paper-napkins", description: "Paper essentials for tables, pantries and food service.", icon: "PackageCheck", tone: "sand" },
  { id: "cat-handwash", parentId: "cat-washroom", name: "Hand Wash", slug: "hand-wash", description: "Hand wash for washrooms and everyday care.", icon: "Droplets", tone: "mint" },
  { id: "cat-dispensers", parentId: "cat-washroom", name: "Dispensers", slug: "dispensers", description: "Dispensers for shared washrooms and workplaces.", icon: "Droplets", tone: "mint" },
  { id: "cat-floor", parentId: "cat-cleaning", name: "Floor & Surface Care", slug: "floor-surface-care", description: "Cleaning supplies for floors and everyday surfaces.", icon: "Sparkles", tone: "sky" },
  { id: "cat-bags", parentId: "cat-disposable", name: "Garbage Bags", slug: "garbage-bags", description: "Waste bags for everyday workplace requirements.", icon: "Trash2", tone: "sand" },
);

const sharedProduct = {
  category: "Tissue & Paper Wholesale",
  categorySlug: "tissue-paper-products",
  brand: "Unbranded",
  price: 0,
  priceOnRequest: true,
  unitsPerCarton: 0,
  minimumOrderCartons: 1,
  stock: 100,
  lowStockThreshold: 5,
  bulkPricing: true,
  allowBackorder: true,
  image: "/images/products/tissue.svg",
  gallery: ["/images/products/tissue.svg"],
  description:
    "Supplied in wholesale cartons for commercial requirements. Carton packing, availability and price are confirmed by Pak Multilinks before the order is finalized.",
  attributes: [
    { name: "Supply unit", value: "Carton" },
    { name: "Inner quantity", value: "Wholesale Carton" },
    { name: "Pricing", value: "Bulk quotation" },
  ],
} satisfies Omit<
  Product,
  "id" | "slug" | "name" | "sku" | "shortDescription"
>;

// Transcribed and catalog products with visual imagery across all categories
export const products: Product[] = [
  {
    ...sharedProduct,
    id: "prod-pop-up",
    slug: "pop-up",
    name: "Pop Up Tissues",
    category: "Facial Tissues",
    categorySlug: "facial-tissues",
    parentCategorySlug: "tissue-paper-products",
    sku: "DEMO-POP-UP",
    image: "/images/products/tissue.svg",
    gallery: ["/images/products/tissue.svg"],
    shortDescription: "Wholesale Pop Up tissue cartons for offices & events.",
    featured: true,
    bestSeller: true,
  },
  {
    ...sharedProduct,
    id: "prod-pantry-pack",
    slug: "pantry-pack",
    name: "Pantry Pack",
    sku: "DEMO-PANTRY-PACK",
    image: "/images/products/tissue.svg",
    gallery: ["/images/products/tissue.svg"],
    shortDescription: "Pantry Pack supplied for bulk commercial pantry requirements.",
    featured: true,
  },
  {
    ...sharedProduct,
    id: "prod-pantry-white",
    slug: "pantry-white",
    name: "Pantry White",
    sku: "DEMO-PANTRY-WHITE",
    image: "/images/products/tissue.svg",
    gallery: ["/images/products/tissue.svg"],
    shortDescription: "Pantry White product available in wholesale cartons.",
    featured: true,
  },
  {
    ...sharedProduct,
    id: "prod-mambo-roll",
    slug: "mambo-roll",
    name: "Mambo Roll",
    category: "Tissue Rolls",
    categorySlug: "tissue-rolls",
    parentCategorySlug: "tissue-paper-products",
    sku: "DEMO-MAMBO-ROLL",
    image: "/images/products/tissue.svg",
    gallery: ["/images/products/tissue.svg"],
    shortDescription: "Mambo Roll supplied carton-wise for business washrooms.",
    featured: true,
  },
  {
    ...sharedProduct,
    id: "prod-mambo-8-plus-2",
    slug: "mambo-8-plus-2",
    name: "Mambo 8+2",
    sku: "DEMO-MAMBO-8-2",
    image: "/images/products/tissue.svg",
    gallery: ["/images/products/tissue.svg"],
    shortDescription: "Mambo 8+2 supplied as a wholesale carton product.",
  },
  {
    ...sharedProduct,
    id: "prod-soft-pack-p",
    slug: "soft-pack-p",
    name: "Soft Pack P",
    category: "Soft Pack Tissues",
    categorySlug: "soft-pack-tissues",
    parentCategorySlug: "tissue-paper-products",
    sku: "DEMO-SOFT-PACK-P",
    image: "/images/products/tissue.svg",
    gallery: ["/images/products/tissue.svg"],
    shortDescription: "Soft Pack P available for carton-based bulk supply.",
  },
  {
    ...sharedProduct,
    id: "prod-soft-pack-regular",
    slug: "soft-pack-regular",
    name: "Soft Pack Regular",
    category: "Soft Pack Tissues",
    categorySlug: "soft-pack-tissues",
    parentCategorySlug: "tissue-paper-products",
    sku: "DEMO-SOFT-PACK-REG",
    image: "/images/products/tissue.svg",
    gallery: ["/images/products/tissue.svg"],
    shortDescription: "Soft Pack Regular supplied in wholesale cartons.",
  },
  {
    ...sharedProduct,
    id: "prod-floor-cleaner",
    slug: "commercial-floor-cleaner",
    name: "Commercial Floor Cleaner 5L",
    category: "Cleaning Products",
    categorySlug: "cleaning-products",
    parentCategorySlug: "cleaning-products",
    sku: "DEMO-FLOOR-5L",
    image: "/images/products/floor-cleaner.svg",
    gallery: ["/images/products/floor-cleaner.svg"],
    shortDescription: "Heavy-duty commercial floor disinfectant and cleaner.",
    featured: true,
    bestSeller: true,
    unitsPerCarton: 4,
  },
  {
    ...sharedProduct,
    id: "prod-disinfectant-spray",
    slug: "multi-surface-spray",
    name: "Multi-Surface Disinfectant Spray",
    category: "Cleaning Products",
    categorySlug: "cleaning-products",
    parentCategorySlug: "cleaning-products",
    sku: "DEMO-SPRAY-500ML",
    image: "/images/products/spray.svg",
    gallery: ["/images/products/spray.svg"],
    shortDescription: "Antibacterial multi-surface disinfectant spray for tables and counters.",
    featured: true,
    unitsPerCarton: 12,
  },
  {
    ...sharedProduct,
    id: "prod-commercial-handwash",
    slug: "commercial-hand-wash",
    name: "Antibacterial Hand Wash 5L Gallon",
    category: "Washroom Supplies",
    categorySlug: "washroom-supplies",
    parentCategorySlug: "washroom-supplies",
    sku: "DEMO-HANDWASH-5L",
    image: "/images/products/hand-wash.svg",
    gallery: ["/images/products/hand-wash.svg"],
    shortDescription: "Gentle lathering antibacterial hand wash for office and restaurant restrooms.",
    featured: true,
    bestSeller: true,
    unitsPerCarton: 4,
  },
  {
    ...sharedProduct,
    id: "prod-auto-dispenser",
    slug: "touchless-soap-dispenser",
    name: "Automatic Sensor Soap Dispenser",
    category: "Dispensers",
    categorySlug: "dispensers",
    parentCategorySlug: "washroom-supplies",
    sku: "DEMO-DISPENSER-AUTO",
    image: "/images/products/dispenser.svg",
    gallery: ["/images/products/dispenser.svg"],
    shortDescription: "Touchless wall-mounted automatic soap & sanitizer dispenser.",
    featured: true,
    unitsPerCarton: 10,
  },
  {
    ...sharedProduct,
    id: "prod-garbage-bags-heavy",
    slug: "heavy-duty-garbage-bags",
    name: "Heavy-Duty Black Garbage Bags 55 Gal",
    category: "Garbage Bags",
    categorySlug: "garbage-bags",
    parentCategorySlug: "disposable-items",
    sku: "DEMO-GARBAGE-55G",
    image: "/images/products/garbage-bags.svg",
    gallery: ["/images/products/garbage-bags.svg"],
    shortDescription: "Tear-resistant extra strong garbage bags for commercial waste.",
    featured: true,
    bestSeller: true,
    unitsPerCarton: 100,
  },
  {
    ...sharedProduct,
    id: "prod-nitrile-gloves",
    slug: "disposable-gloves",
    name: "Disposable Nitrile Gloves (Pack 100)",
    category: "Disposable Items",
    categorySlug: "disposable-items",
    parentCategorySlug: "disposable-items",
    sku: "DEMO-GLOVES-NITRILE",
    image: "/images/products/gloves.svg",
    gallery: ["/images/products/gloves.svg"],
    shortDescription: "Powder-free durable hygiene gloves for food handling and cleaning.",
    featured: true,
    unitsPerCarton: 10,
  },
  {
    ...sharedProduct,
    id: "prod-industrial-mop",
    slug: "industrial-wet-mop",
    name: "Industrial Floor Wet Mop with Handle",
    category: "Floor & Surface Care",
    categorySlug: "floor-surface-care",
    parentCategorySlug: "cleaning-products",
    sku: "DEMO-MOP-INDUSTRIAL",
    image: "/images/products/mop.svg",
    gallery: ["/images/products/mop.svg"],
    shortDescription: "Heavy-duty commercial cotton loop mop for large hall and office floors.",
    featured: true,
    unitsPerCarton: 6,
  },
  {
    ...sharedProduct,
    id: "prod-microfiber-cloths",
    slug: "microfiber-cleaning-cloths",
    name: "Microfiber Cleaning Cloths (Pack of 12)",
    category: "Cleaning Products",
    categorySlug: "cleaning-products",
    parentCategorySlug: "cleaning-products",
    sku: "DEMO-MICROFIBER-12PK",
    image: "/images/products/cloth.svg",
    gallery: ["/images/products/cloth.svg"],
    shortDescription: "Lint-free, scratch-free microfiber cloths for glass, desks and cars.",
    featured: true,
    unitsPerCarton: 20,
  },
];

export const featuredProducts = products.filter((product) => product.featured);
export const brands = [...new Set(products.map((product) => product.brand))];

export function getProduct(slug: string) {
  return products.find((product) => product.slug === slug);
}

export function getCategory(slug: string) {
  return categories.find((category) => category.slug === slug);
}

export function getPrice(product: Product) {
  return product.salePrice ?? product.price;
}
