import assert from 'node:assert/strict';
import nextEnv from '@next/env';
import { PrismaClient } from '@prisma/client';
import { SignJWT } from 'jose';
nextEnv.loadEnvConfig(process.cwd());
const base = process.env.TEST_BASE_URL || 'http://localhost:3003';
const local = ['localhost', '127.0.0.1'];
if (!local.includes(new URL(base).hostname) || !local.includes(new URL(process.env.DATABASE_URL).hostname)) throw new Error('Run these integration checks against a local app and database only.');
const db = new PrismaClient();
const prefix = `verify-${Date.now()}`;
const secret = process.env.AUTH_SECRET || process.env.JWT_SECRET || 'pmh-local-development-secret-change-me';
const token = await new SignJWT({ email: 'verification@example.test', name: 'Local verification', role: 'ADMIN' }).setProtectedHeader({ alg: 'HS256', typ: 'JWT' }).setSubject('verification').setIssuedAt().setExpirationTime('10m').setIssuer('pak-multilinks-hygiene').setAudience('pak-multilinks-web').sign(new TextEncoder().encode(secret));
const headers = { 'Content-Type': 'application/json', Cookie: `pmh_session=${token}`, Origin: base };
const ids = [];
const categoryIds = [];
const request = (path, method, body, authenticated = true) => fetch(`${base}${path}`, { method, headers: authenticated ? headers : { 'Content-Type': 'application/json' }, body: body ? JSON.stringify(body) : undefined });
const pricing = row => ({ id: row.id, updatedAt: row.updatedAt.toISOString(), price: Number(row.price), salePrice: row.salePrice === null ? null : Number(row.salePrice), priceOnRequest: row.priceOnRequest, stock: row.stock, unitsPerCarton: row.unitsPerCarton, minimumOrderCartons: row.minimumOrderCartons });
try {
  assert.equal((await request('/api/admin/products/pricing', 'PATCH', { products: [] }, false)).status, 401);
  const root = await db.category.create({ data: { name: 'Verification parent', slug: `${prefix}-parent` } }); categoryIds.push(root.id);
  const response = await request('/api/admin/categories', 'POST', { name: 'Verification child', slug: `${prefix}-child`, parentId: root.id });
  assert.equal(response.status, 201);
  const child = (await response.json()).category; categoryIds.push(child.id);
  assert.equal((await request('/api/admin/categories', 'POST', { name: 'Invalid grandchild', slug: `${prefix}-grandchild`, parentId: child.id })).status, 400);
  assert.equal((await request(`/api/admin/categories/${root.id}`, 'PATCH', { name: root.name, slug: root.slug, parentId: root.id })).status, 400);
  const a = await db.product.create({ data: { name: 'Verification tissue A', slug: `${prefix}-a`, sku: `${prefix}-A`, description: 'Temporary local verification fixture.', price: 100, salePrice: 90, priceOnRequest: false, stock: 10, unitsPerCarton: 12, minimumOrderCartons: 1, categoryId: child.id, status: 'ACTIVE' } }); ids.push(a.id);
  const b = await db.product.create({ data: { name: 'Verification tissue B', slug: `${prefix}-b`, sku: `${prefix}-B`, description: 'Temporary local verification fixture.', price: 100, stock: 10, categoryId: child.id, status: 'ACTIVE' } }); ids.push(b.id);
  let result = await request('/api/admin/products/pricing', 'PATCH', { products: [{ ...pricing(a), price: 125.50, salePrice: 110.25 }] });
  assert.equal(result.status, 200, await result.text());
  const saved = await db.product.findUniqueOrThrow({ where: { id: a.id } });
  assert.equal(Number(saved.price), 125.5); assert.equal(Number(saved.salePrice), 110.25);
  const catalog = await (await fetch(`${base}/api/catalog`)).json();
  assert.equal(catalog.products.find(row => row.id === a.id).salePrice, 110.25);
  assert.equal(catalog.products.find(row => row.id === a.id).parentCategorySlug, root.slug);
  result = await request('/api/admin/products/pricing', 'PATCH', { products: [{ ...pricing(saved), salePrice: 200 }] }); assert.equal(result.status, 400);
  result = await request('/api/admin/products/pricing', 'PATCH', { products: [{ ...pricing(saved), price: 1.001 }] }); assert.equal(result.status, 400);
  result = await request('/api/admin/products/pricing', 'PATCH', { products: [{ ...pricing(saved), stock: -1 }] }); assert.equal(result.status, 400);
  await db.product.update({ where: { id: b.id }, data: { stock: 20 } });
  result = await request('/api/admin/products/pricing', 'PATCH', { products: [{ ...pricing(saved), price: 999 }, pricing(b)] }); assert.equal(result.status, 409);
  assert.equal(Number((await db.product.findUniqueOrThrow({ where: { id: a.id } })).price), 125.5, 'Batch must roll back on a stale row');
  result = await request(`/api/admin/categories/${root.id}`, 'DELETE'); assert.equal(result.status, 200);
  const hidden = await (await fetch(`${base}/api/catalog`)).json();
  assert.ok(!hidden.products.some(row => ids.includes(row.id)), 'Archived parent products must be hidden');
  assert.ok(!hidden.categories.some(row => row.id === child.id), 'Archived parent children must be hidden');
  console.log('PASS: admin authentication, decimal pricing persistence, storefront synchronization, invalid prices/stock, atomic stale-edit rollback, two-level categories, and archive visibility.');
} finally {
  await db.product.deleteMany({ where: { id: { in: ids } } });
  for (const id of categoryIds.reverse()) await db.category.delete({ where: { id } });
  await db.$disconnect();
}
